name = "printer"
version = "0.1.0"
description = "A Gleam project"
gleam = ">= 0.32.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
glerm = { path = "../../" }
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_stdlib = ">= 0.65.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
